### ISSUE TITLE
I've been recoded it for 1.13, please have a look

### ISSUE THREAD

**Issue by SuperColaTyphoon** [yodalee/FastBuild#7]
[FastBuild.zip](https://github.com/yodalee/FastBuild/files/2240457/FastBuild.zip)
(UPDATED)

just added some tiny tweaks to make it compatible with 1.13, please check if it works or not

**Comment by yodalee** [comment]
Hello and thank for contribution.
However, it is difficult to me to compare and see where the difference is. Maybe you can try to send a Pull Request to this repository. Also, if you like, you can briefly describe what you have done and why.
If you don't know how to make contribution. I have written a brief instruction about it.
https://yodalee.blogspot.com/2014/05/pull-requestgithub.html
